### ISSUE TITLE
External monitor on razer blade 15

### ISSUE THREAD

**Issue by medpar** [mdezc/Razer-Blade-15-Base-2021-Hackintosh#1]
After successfully setting up my hackintosh with macos big sur, I need to connect an external monitor to my razer blade 15. I am aware that both the HDMI and usb-c thunderbolt ports are connected to the nvidia graphics card. However, I would like to find some solution other than buying a displaylink device, as these are very expensive and hard to get in my country.
Is there any way to patch the device to get the intel graphics out of the hdmi or usb-c port?

**Comment by mdezc** [comment]
I tried a few things with a WD15 Dell dock that I couldn't get to work, not sure if I missed anything or it simply doesn't work due to the dock having a USBC adapter. 🤷
